kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: o9e9a8DuPBkoFh8EzpiAzjO3j/az6nIWux632gR7v/U=
      - identity: {}
