---
#- name: Install Base System
#  hosts: base, kubernetes
    
#  tasks:
  
#  - name: Configure base libvirt dns
#    include_tasks: 10_configure_libvirt_network.yaml

#  - name: Configure kubernetes master, workers and etcd servers
#    include_tasks: 20_instalar_herramientas.yaml

