---
- name: Install Base System
  hosts: kubernetes
  become: true
  become_user: root   
    
  tasks:
  
    - name: Configure base ubuntu k8s
      include_tasks: 20_instalar_herramientas.yaml

    - name: Configure systemd and ssh key
      include_tasks: 30_create_ssh_key_pair.yaml

