---
- name: setear timezone y generar llaves ssh
  hosts: kubernetes
  become: true
  become_user: root  
  
  tasks: 
  
  - name: Set timezone to America/Santiago
    community.general.timezone:
      rtc: UTC
      name: America/Santiago

  - name: generate SSH key
    community.crypto.openssh_keypair:
      path: "~/.ssh/id_ed25519"
      type: ed25519
      size: 4096
      state: present
      force: yes

  - name: Copiar machine.txt
    ansible.builtin.copy:
      src: /home/user1/github/05_createVM/ansible/01_deploy_base/resources/machine.txt
      #src: /home/pablo/documentos/informatica/linux/certificaciones/05_createVM/ansible/01_deploy_base/resources/machine.txt
      dest: /root/
      owner: root
      group: root

  - name: Copiar ssh_copy_key.sh
    ansible.builtin.copy:
      src: /home/user1/github/05_createVM/ansible/01_deploy_base/resources/ssh_copy_key.sh
      #src: /home/pablo/documentos/informatica/linux/certificaciones/05_createVM/ansible/01_deploy_base/resources/ssh_copy_key.sh
      dest: /root/
      owner: root
      group: root
      mode: "0555"
      
  #- name: Run ssh_copy_key.sh
  #  ansible.builtin.script:
  #    cmd: /root/ssh_copy_key.sh 
  #  delegate_to: localhost  
    #when: inventory_hostname in groups['kubernetes']  
  - name: Run ssh copy-id
    ansible.builtin.shell: |
      while read IP FQDN HOST POD_SUBNET SVC_SUBNET; 
      do ssh-copy-id -o StrictHostKeyChecking=no root@${IP};
      done < /root/machine.txt
    args:
      chdir: /root/  
    delegate_to: localhost
