---
- name: Instalar herramientas
  hosts: kubernetes
  become: true
  become_user: root  
  
  tasks: 

  - name: instalar herramientas
    become: true
    become_user: root  
    ansible.builtin.apt:
      pkg: 
        - git
        - wget
        - curl
        - vim-nox
        - openssl
        - bash-completion
        - elinks
        - sshpass  
      state: present
    when: inventory_hostname in groups['kubernetes']   
  
