#cloud-config
disable_root: 0
users:
  - name: user1
    hashed_passwd: $6$undrHptAkQLHjxsv$qypMOxFgPomyaNBNVAtJbxeG2TjJKaFU79b8I5t.viNj/cRb/Y8Rtl4G1WrTSrbq9ZIZ2EkamQS/k3JJOAhFF/ 
    ssh_pwauth: true
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICcVbfuPhmpEw1wASVMql5rUgC9Xo5V+shwXECgc813g pablo@kuberlab.local
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    disable_root: 0
    groups: sudo
    add lock_passwd: false
    shell: /bin/bash
#user-data:
#  chpasswd:
#    expire: false
#      list:
#        - user1: $6$undrHptAkQLHjxsv$qypMOxFgPomyaNBNVAtJbxeG2TjJKaFU79b8I5t.viNj/cRb/Y8Rtl4G1WrTSrbq9ZIZ2EkamQS/k3JJOAhFF/

#chpasswd:
#  expire: false
#  users:
#  - {name: root, password: password, type: text}
    
#chpasswd:
#  list: |
#    root:$6$undrHptAkQLHjxsv$qypMOxFgPomyaNBNVAtJbxeG2TjJKaFU79b8I5t.viNj/cRb/Y8Rtl4G1WrTSrbq9ZIZ2EkamQS/k3JJOAhFF/
#  expire: False    
runcmd:
  - sed -i 's/^Defaults.*requiretty/#&/g' /etc/sudoers
  - sed -i -e '$aUseDNS no' /etc/ssh/sshd_config
  - sed -i 's/^GSSAPIAuthentication\ yes/GSSAPIAuthentication\ no/g' /etc/ssh/sshd_config
  - sed -i 's/^PasswordAuthentication\ no/PasswordAuthentication\ yes/g' /etc/ssh/sshd_config
  - sed -i 's/^PermitRootLogin\ no/PermitRootLogin\ yes/g' /etc/ssh/sshd_config
  - echo "root ALL=(ALL:ALL) ALL" >> /etc/sudoers
  - sysctl kernel.sysrq=1
