---
#- name: setear timezone, generar y distribuir llaves ssh
#  hosts: kubernetes
#  become: true
#  become_user: root  
#  vars:
#    - private: "/root/.ssh/id_ed2551"
  
#  tasks: 
  
  - name: generate SSH key
    community.crypto.openssh_keypair:
      path: "~/.ssh/id_ed25519"
      type: ed25519
      size: 4096
      state: present
      force: yes
      mode: 0600  

  - name: Copiar machine.txt
    ansible.builtin.copy:
      src: /home/user1/github/05_createVM/ansible/01_deploy_base/10_cluster/resources/machine.txt
      #src: /home/pablo/documentos/informatica/linux/certificaciones/05_createVM/ansible/01_deploy_base/10_cluster/resources/machine.txt
      dest: /root/
      owner: root
      group: root

  - name: ssh agent
    ansible.builtin.shell: |
      eval "$(ssh-agent -s)"
      ssh-add
    delegate_to: "{{inventory_hostname}}"
  
  - name: Run ssh copy-id
    ansible.builtin.shell: |
      while read IP FQDN HOST POD_SUBNET SVC_SUBNET; 
      do sshpass -p password ssh-copy-id -o StrictHostKeyChecking=accept-new root@${IP};
      done < /root/machine.txt
    args:
      chdir: /root/  
    delegate_to: "{{ inventory_hostname }}"
